name = "MiniObserve"
uuid = "fcdc8f60-d396-456b-adf3-1a67625f7fcb"
authors = ["Martin Hinsch <hinsch.martin@gmail.com>"]
version = "0.3.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.6"
DocStringExtensions = "0.9"
MacroTools = "0.5"
Reexport = "1.2"
